### ISSUE TITLE
Update blog title

### ISSUE THREAD

**Issue by TrashBirdEcology** [maelle/simplymaelle#31]
['know the seeds](https://github.com/maelle/simplymaelle/blob/master/content/post/2017-04-12-seeds.md)' -> 'harvest the seeds'

**Comment by maelle** [comment]
why? :-)

**Comment by TrashBirdEcology** [comment]
because its awesome :)

*______________________________________________________*

Jessica L. Burnett (she/her)

Mendenhall Postdoctoral Fellow & Research Ecologist

US Geological Survey Science Analytics and Synthesis
<https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis>

Github <http://github.com/trashbirdecology>

ORCID: 0000-0002-0896-5099
<https://orcid.org/0000-0002-0896-5099>
*______________________________________________________*


Join the Community for Data Integration <https://www.usgs.gov/centers/cdi>! All
welcome. It's cool.

**Comment by maelle** [comment]
I'm not sure I follow? My original blog post title is an admittedly bad pun, "know" the seeds because it is a study of a seeds sample.
